---
title: "Final Report"
author: "twitter260"
output: html_document
---
# Final Report

### Overview and Motivation
Social media in rallies has been cited as a potential model for the interactions that occur through conventional means. However, there is conflicting empirical evidence of the efficacy of the “Twitter Revolution” phenomenon. Considering recent rallies between alt-right and liberal parties that escalated to violence and destruction of property, namely Charlottesville, we attempt to assess the validity of the Twitter Revolution hypothesis by analyzing tweets in a 50-mile catchment area surrounding Murfreesboro and Shelbyville during the Shelbyville White Lives Matter rallies and Murfreesboro Loves counter-protest on October 28, 2017. In this project, we identify primary networks of communication from October 27 to October 29. We employ sentiment analysis to identify positive and negative content, and assess similarities between the sentiment value of Twitter content through identified communication pathways and events that occur on the ground.

### Related Work
Between the 11th and 12th of August, white-nationalists flocked to Charlottesville, Virginia for the Unite the Right rally. On the night of August 11th, white nationalists carrying lit tiki torches and shouting anti-semitic and white-supremacist chants famously marched through the University of Virginia campus. They encountered a group of counter-protesters and a small fight ensued between the two parties. These events escalated the following day as protesters and counter-protesters gathered at Emancipation park. Many protesters and counter-protesters were armed, and the Charlottesville Police department pulled back. This set the stage for a violent engagement between the two parties. Before the rally began, protesters and counter-protesters faced off, kicking, punching, hurling water bottles at and deploying chemical sprays against one another. At least 14 people were injured in the ensuing violence. Charlottesville declared a state of emergency, and the Virginia State Police declared that the gathering was unlawful. After the rally had been legally disbanded, protesters moved to McIntire Park and counter-protesters continued marching against the white-nationalists. Ultimately, the protest turned deadly as James Field accelerated into a crowd of counter-protesters and then fled the scene, leaving 19 injured and killing Heather Heyer. This event received national attention and was widely condemned by politicians. Donald Trump was rightfully criticized for his comments regarding the protesters. 


### Initial Questions
During this event, little attention was given to social media use in Charlottesville. However, due to widespread and persistent use of social media, attendees and Charlottesville residents were likely using social media as a way to voice opinions and organize collective actions. Building upon this hypothesis, we first set out to see if people in Charlottesville who were actively tweeting during the event were collectively organizing and either influencing or reacting to the event through their content. However, due to limitations of Twitter’s API we had to use another protest for the basis of our analysis. We opted to use the Shelbyville and Murfreesboro protests as the motivation for our analysis due to its initial similarities with the Charlottesville event. Due to the variety of content, it was difficult to categorize tweets into groups based on verbal content. Instead we used sentiment analysis to quantify the emotional value of tweets. Other considerations were given to location within the catchment area, but spatial data was not precise enough to allow for sentiment analysis by location. Our analyses evolved into looking at the sentiment score of each tweet and the network of interactions among Twitter accounts to identify trends within the network, important Twitter accounts within the network, and changing sentiments over time using the protests as a comparative event.

### Data
Using the twitteR package developed by Jeff Gentry, we accessed the Twitter Streaming API and obtained all tweets between 00:00:01 October 27, 2017 and 23:59:59 October 29, 2017. The data represents 65,955 different tweets from 22,209 unique Twitter accounts. To further simplify our analysis, we rounded time into 15 minute increments.     

Tweets were prepared for analysis using regular expression functions in base R 3.4.2 and the stringr package developed by Hadley Wickham. Each tweet was systematically changed to only lower case letters, and subsequently had stop words removed. Stop words are natural language words which have very little meaning, such as "and", "the", "a", "an", and similar words. Residual text including UTF-8 emojis, punctuation, replies (@), retweets, linefeeds, and URLs were removed. To deal with foreign languages, the text was converted to ASCII-Latin 1 characters and we only preserved ASCII-Latin 1 lower case letters. 

### Exploratory Analysis
Initially, the resultant network of interactions between Twitter accounts with connections weighted by sentiment score did not reveal any insights into the nature of communication amongst Twitter users. Treating the social network as directed did not seem feasible due to the large volume of data and sparsity of the adjacency matrix so we did not consider directionality of content. Additionally, some tweets had a sentiment score of 0, so to preserve the connection we made the weight arbitrarily small (10^-6). Finally, eighty-three percent of interactions among Twitter accounts could be classified as closed dyads where an account interacts with only one other account. We instead focused on the largest components that existed within the network. We filtered by component size, and selected the fifteen largest components for further analysis.  Although each of the 15 largest components could be divided into an equal number of components representing positive and negative interactions, the largest connected component contained eighty-three percent of the Twitter accounts and eighty-six percent of connections within the filtered network and preserved many of the topological features, including degree frequency; triangles; and weights, of the graph, so we opted to solely analyze the largest connected component.  

We began by comparing the distribution of weights which represented the sentiment score of a connection in the overall network to the distribution of weights in the largest connected component. In both instances we observed bimodal distributions with peaks at three and negative three, but the histogram suggested that the largest connected component had slightly more negative weights. We conducted a t-test on the weights of the largest connected and complete graph using pooled variance, and did not find any discernible difference. 

We then created a movie-panel representation of the graph to assess the development of the network over time. We grouped the edges by time when they were added into eight categories and plotted the graph, adding new vertices and edges accordingly. We noted that the graph is sparsely connected up until the fifth iteration. At this time, we can identify several clusters beginning to form within the network of interactions. By the sixth iteration, very few new accounts are beginning to interact with the network. Instead, previously participating Twitter users are almost exclusively interacting with those in the network where most of those users began participating over the course of the 28th of October, or the day of the protest. This tentatively supports the Twitter Revolution theory and begins to take steps towards answering our primary question. 

We then set out to identify “key-players” in the communication network. We initially sought to use a combination of authority and hub scores to identify the accounts with the highest degree of influence. However, because the network was treated as undirected initially, the authority and hub scores were the same for each account in the network. We ultimately chose to use hub scores and degree centrality as our primary measures.   

Hub scores were an imperfect measure of importance in our network. The densest communities existed around realDonaldTrump and DeLoachJW. Many of the most important hubs were identified in these neighborhoods and had no distinguishing features besides being periphery accounts who interacted with realDonaldTrump, DeLoachJW, and one other account with a high degree. However, hub scores did allow us to identify DeLoachJW as being the most influential account in the network. DeLoachJW interacted with other major accounts, had his actions reciprocated, and connected many communities across a wide spectrum of content. 

We finally attempted to represent our largest connected component as a heat graph, to give the user a more intuitive idea of the structure of the network. However, the adjacency matrix was sparse, and consequently the heat graph of the connections was not informative. We instead provide a toy example of our third largest identified network. The network consisted of twenty-seven accounts and connections between the accounts. To make the heatmap more informative, we attempted to use a clustering algorithm to identify the channels of communication. We then applied this clustering algorithm to a random sample of accounts in our main network. We saw that clustering using the negative distance matrix is a valid method of identifying communities within the network but chose not to pursue this for our final analysis.   


### Final Analysis
Social networks are complex systems that can evolve indefinitely. Treating the interactions between Twitter accounts in the greater Murfreesboro Shelbyville as a single large network was impossible due to structural holes amongst thousands of components, many of which represent only a single pair of Twitter users. Instead, focusing on the largest connected component yielded some useful insights. 

Similarly to the overall network on a macro-level, the largest component contained a roughly equal number of positive and negative interactions which aligned with the trend previously identified in the overall network. Focusing on the micro-level structure of the network, the largest component contained the only two triadic closures present within the overall network. These triads were the largest cliques present as well. Due to the lack of triadic closure, the network can be imagined as strings of dyadic relationships without a strong tendency to close and form triads.

The most interesting relationships were observed on the meso-level structure. The degree distribution of the largest connected component approximates the power law, with an average degree of 2.19. However, it was not uncommon to observe Twitter users with many connections; over five-percent of users had more than six connections and the top one-percent of accounts had no fewer than fifteen connections. Summarily, the network could be modeled as a scale-free network with preferential attachment partially determined by time.

The importance of the time-dependent preferential attachment is illustrated in the movie-pane image of the development of the graph. Seventy-eight percent of nodes had been added to the network by the sixth interval. Coincidentally, this time corresponds with the afternoon of the events in question. Ninety-two percent of nodes had been added to the network by the seventh interval which corresponds to the evening of the event in question. We observe that the network becomes nearly “complete” at this time. The probability of joining the network is also highest during these two contiguous time frames.  Two possible explanations for this phenomenon is people are either reaction to the protests retrospectively or people begin reacting to the University of Tennessee-University of Kentucky football game.

Undoubtedly though, the network incorporates both tweets about the protests and football. Within the network, we see two communities formed, connected by both hubs and accounts with many connections. From this we are able to identify key players which were used in the sentiment analysis. Key players included but were not limited to @Limbaugh2016, @realDonaldTrump, @DeLoachJW, and @BigBoyVol.  

